[build]
builder = "dockerfile"

[deploy]
startCommand = "/bin/sh -c 'uvicorn app.api.main:app --host 0.0.0.0 --port $PORT'"
healthcheckPath = "/health/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"